apiVersion: apps/v1
kind: Deployment
metadata:
  name: felixhub
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: felixhub
  template:
    metadata:
      labels:
        app: felixhub
    spec:
      containers:
        - name: felixhub
          image: feelfeel200088/felixhub.dev  # Your Docker image
          ports:
            - containerPort: 8080  # Port inside the container
