apiVersion: apps/v1
kind: Deployment
metadata:
  name: felixhub
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: felixhub
  template:
    metadata:
      labels:
        app: felixhub
    spec:
      containers:
        - name: felixhub
          image: feelfeel200088/felixhub:latest  # Your Docker image
          ports:
            - containerPort: 8080  # Port inside the container

---
apiVersion: v1
kind: Service
metadata:
  name: felixhub-internal
spec:
  selector:
    app: felixhub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Internal service, only accessible inside the cluster

---
apiVersion: v1
kind: Service
metadata:
  name: felixhub-external
spec:
  selector:
    app: felixhub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  # Static port exposed on all nodes
  type: NodePort  # Expose the service externally using NodePort
