apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok:alpine
          ports:
            - containerPort: 80
            # - containerPort: 4040 if you want web
          env:
            - name: NGROK_CONFIG
              value: "/etc/ngrok/ngrok.yaml"
          volumeMounts:
            - name: ngrok-config-volume
              mountPath: /etc/ngrok
              readOnly: true
      volumes:
        - name: ngrok-config-volume
          configMap:
            name: ngrok-config
            items:
              - key: ngrok.yaml
                path: ngrok.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: utility
spec:
  selector:
    app: ngrok
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # Expose ngrok HTTP port
    # - protocol: TCP
    #   port: 4040
    #   targetPort: 4040 # Expose ngrok Web Inspector port
  type: ClusterIP   # You can use LoadBalancer or NodePort for external access
