apiVersion: v1
kind: Service
metadata:
  name: felixhub-external
spec:
  selector:
    app: felixhub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
