replicaCount: 1

image:
  repository: feelfeel200088/felixhub.dev
  tag: latest

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

service:
  external:
    enabled: true
    nodePort: 30001
