apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-felixhub
  labels:
    app: felixhub
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: felixhub
  template:
    metadata:
      labels:
        app: felixhub
    spec:
      serviceAccountName: {{ default (printf "%s-felixhub" .Release.Name) .Values.serviceAccount.name }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: felixhub
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
