apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-felixhub-internal
  labels:
    app: felixhub
spec:
  selector:
    app: felixhub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
